[pytest]
pythonpath = ..

testpaths = tests

addopts =
    --base-url=http://localhost:3000
    --browser=chromium
    --strict-markers
    --tb=short
    --capture=no
    --color=yes

norecursedirs = .venv .git __pycache__ target

markers =
    smoke: Run critical path tests
    functional: Run functional validation tests
    regression: Run full suite
